name: guide
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
  - plotly
  - defaults
dependencies:
  # mdanalysis dependencies
  - matplotlib
  - networkx
  - openmm>=7.0.0
  - packaging
  - parmed
  - scikit-learn>=1.1.2
  - threadpoolctl
  - pyedr>=0.7
  # building documentation
  - docutils
  - pandoc
  - pybtex
  - sphinx
  - sphinxcontrib-bibtex
  # used by custom_parallel_analysis.ipynb
  - graphviz
  - tabulate
  - python-graphviz
  # used in multiple notebooks
  - jupyter_contrib_nbextensions
  - nbconvert
  - nbformat
  - nglview
  - notebook<7
  - seaborn>=0.12.1
  # used in pairwise_rmsd.ipynb
  - plotly
  # used in custom_parallel_analysis.ipynb
  - distributed==2021.1.0
  - dask==2021.1.0
  # used in density_analysis.ipynb
  - ipygany
  # used in density_analysis.ipynb
  - pyvista
  # used in density_analysis.ipynb
  - scikit-image
  # used in aligning_trajectory.ipynb
  - moviepy
  # used in conf.py
  - ipython
  - ipywidgets<8.0.0
  - nbsphinx
  # used for notebook testing
  - pytest
  - python=3.9
  - pip
  - pip:
      # used in conf.py
      - msmb_theme
      - sphinx_rtd_theme
      - sphinx-sitemap
      # used for notebook testing
      - nbval
      # developer tooling
      - pre-commit
      # mdanalysis and its tests and test data
      - git+https://github.com/MDAnalysis/mdanalysis@develop#egg=mdanalysis&subdirectory=package
      - git+https://github.com/MDAnalysis/mdanalysis@develop#egg=MDAnalysisTests&subdirectory=testsuite
      - git+https://github.com/MDAnalysis/MDAnalysisData@master#egg=MDAnalysisData
